/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.basara.view;

import java.awt.*;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author HEWLETT-PACKARD
 */
public class Pegawai extends javax.swing.JFrame {

    /**
     * Creates new form Pengguna
     */
    static boolean Maximize = true;
    int x, y;
    CardLayout cardlayout;
    
    public Pegawai() {
        initComponents();
        cardlayout = (CardLayout) menu.getLayout();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        btnMaximize = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        header2 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        lb_time = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        Beranda = new javax.swing.JPanel();
        pnlBeranda = new javax.swing.JPanel();
        iconBeranda = new javax.swing.JButton();
        btnBeranda = new javax.swing.JButton();
        BeliSampah = new javax.swing.JPanel();
        pnlVerSetoran = new javax.swing.JPanel();
        iconVerSetoran = new javax.swing.JButton();
        btnVerSetoran = new javax.swing.JButton();
        JualProduk = new javax.swing.JPanel();
        pnlVerPengrajin = new javax.swing.JPanel();
        iconVerPengrajin = new javax.swing.JButton();
        btnVerPengrajin = new javax.swing.JButton();
        InformasiAkun = new javax.swing.JPanel();
        pnlSampah = new javax.swing.JPanel();
        iconSampah = new javax.swing.JButton();
        btnSampah = new javax.swing.JButton();
        Deposit = new javax.swing.JPanel();
        pnlProduk = new javax.swing.JPanel();
        iconProduk = new javax.swing.JButton();
        btnProduk = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        beranda = new javax.swing.JPanel();
        verifikasi_setoran = new javax.swing.JPanel();
        jualproduk = new javax.swing.JPanel();
        informasiakun = new javax.swing.JPanel();
        deposit = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 720));

        header.setBackground(new java.awt.Color(0, 128, 128));
        header.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 128, 128)));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnMaximize.setBackground(new java.awt.Color(0, 128, 128));
        btnMaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/max.png"))); // NOI18N
        btnMaximize.setContentAreaFilled(false);
        btnMaximize.setOpaque(true);
        btnMaximize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/max.png"))); // NOI18N
        btnMaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseExited(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(0, 128, 128));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnExit.setContentAreaFilled(false);
        btnExit.setOpaque(true);
        btnExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        btnMinimize.setBackground(new java.awt.Color(0, 128, 128));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/min.png"))); // NOI18N
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setOpaque(true);
        btnMinimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/min.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });

        title.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Beranda - Basara 1.0");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMaximize, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
            .addComponent(btnMaximize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        header2.setBackground(new java.awt.Color(255, 255, 255));
        header2.setForeground(new java.awt.Color(0, 128, 128));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-40.png"))); // NOI18N
        jButton11.setContentAreaFilled(false);

        jButton12.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton12.setText("Nama Pegawai");
        jButton12.setContentAreaFilled(false);
        jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-exit-20.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Logout");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/basara.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Helo,");

        lb_date.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        lb_time.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        javax.swing.GroupLayout header2Layout = new javax.swing.GroupLayout(header2);
        header2.setLayout(header2Layout);
        header2Layout.setHorizontalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header2Layout.createSequentialGroup()
                        .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header2Layout.createSequentialGroup()
                                .addComponent(lb_time, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        header2Layout.setVerticalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(header2Layout.createSequentialGroup()
                .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(header2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lb_time, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(header2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(header2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panel.setBackground(new java.awt.Color(255, 255, 255));

        Beranda.setBackground(new java.awt.Color(0, 128, 128));

        pnlBeranda.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlBerandaLayout = new javax.swing.GroupLayout(pnlBeranda);
        pnlBeranda.setLayout(pnlBerandaLayout);
        pnlBerandaLayout.setHorizontalGroup(
            pnlBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        pnlBerandaLayout.setVerticalGroup(
            pnlBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconBeranda.setBackground(new java.awt.Color(0, 128, 128));
        iconBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30(1).png"))); // NOI18N
        iconBeranda.setContentAreaFilled(false);
        iconBeranda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iconBeranda.setOpaque(true);
        iconBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconBerandaMouseClicked(evt);
            }
        });

        btnBeranda.setBackground(new java.awt.Color(0, 128, 128));
        btnBeranda.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnBeranda.setForeground(new java.awt.Color(255, 255, 255));
        btnBeranda.setText("Beranda");
        btnBeranda.setContentAreaFilled(false);
        btnBeranda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBeranda.setOpaque(true);
        btnBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBerandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBerandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBerandaMouseExited(evt);
            }
        });
        btnBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BerandaLayout = new javax.swing.GroupLayout(Beranda);
        Beranda.setLayout(BerandaLayout);
        BerandaLayout.setHorizontalGroup(
            BerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BerandaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(iconBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        BerandaLayout.setVerticalGroup(
            BerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BerandaLayout.createSequentialGroup()
                .addGroup(BerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnBeranda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        BeliSampah.setBackground(new java.awt.Color(0, 128, 128));

        pnlVerSetoran.setBackground(new java.awt.Color(0, 128, 128));

        javax.swing.GroupLayout pnlVerSetoranLayout = new javax.swing.GroupLayout(pnlVerSetoran);
        pnlVerSetoran.setLayout(pnlVerSetoranLayout);
        pnlVerSetoranLayout.setHorizontalGroup(
            pnlVerSetoranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        pnlVerSetoranLayout.setVerticalGroup(
            pnlVerSetoranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconVerSetoran.setBackground(new java.awt.Color(255, 255, 255));
        iconVerSetoran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-checklist-filled-30.png"))); // NOI18N
        iconVerSetoran.setContentAreaFilled(false);
        iconVerSetoran.setOpaque(true);

        btnVerSetoran.setBackground(new java.awt.Color(255, 255, 255));
        btnVerSetoran.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnVerSetoran.setText("Verifikasi Setoran");
        btnVerSetoran.setContentAreaFilled(false);
        btnVerSetoran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVerSetoran.setOpaque(true);
        btnVerSetoran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerSetoranMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BeliSampahLayout = new javax.swing.GroupLayout(BeliSampah);
        BeliSampah.setLayout(BeliSampahLayout);
        BeliSampahLayout.setHorizontalGroup(
            BeliSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BeliSampahLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlVerSetoran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(iconVerSetoran, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnVerSetoran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        BeliSampahLayout.setVerticalGroup(
            BeliSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BeliSampahLayout.createSequentialGroup()
                .addGroup(BeliSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlVerSetoran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconVerSetoran, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnVerSetoran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        JualProduk.setBackground(new java.awt.Color(0, 128, 128));

        pnlVerPengrajin.setBackground(new java.awt.Color(0, 128, 128));

        javax.swing.GroupLayout pnlVerPengrajinLayout = new javax.swing.GroupLayout(pnlVerPengrajin);
        pnlVerPengrajin.setLayout(pnlVerPengrajinLayout);
        pnlVerPengrajinLayout.setHorizontalGroup(
            pnlVerPengrajinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        pnlVerPengrajinLayout.setVerticalGroup(
            pnlVerPengrajinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconVerPengrajin.setBackground(new java.awt.Color(255, 255, 255));
        iconVerPengrajin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-todo-list-filled-30.png"))); // NOI18N
        iconVerPengrajin.setContentAreaFilled(false);
        iconVerPengrajin.setOpaque(true);

        btnVerPengrajin.setBackground(new java.awt.Color(255, 255, 255));
        btnVerPengrajin.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnVerPengrajin.setText("Verifikasi Pengrajin");
        btnVerPengrajin.setContentAreaFilled(false);
        btnVerPengrajin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVerPengrajin.setOpaque(true);
        btnVerPengrajin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerPengrajinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JualProdukLayout = new javax.swing.GroupLayout(JualProduk);
        JualProduk.setLayout(JualProdukLayout);
        JualProdukLayout.setHorizontalGroup(
            JualProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JualProdukLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlVerPengrajin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(iconVerPengrajin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnVerPengrajin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        JualProdukLayout.setVerticalGroup(
            JualProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JualProdukLayout.createSequentialGroup()
                .addGroup(JualProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlVerPengrajin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconVerPengrajin, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnVerPengrajin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        InformasiAkun.setBackground(new java.awt.Color(0, 128, 128));

        pnlSampah.setBackground(new java.awt.Color(0, 128, 128));

        javax.swing.GroupLayout pnlSampahLayout = new javax.swing.GroupLayout(pnlSampah);
        pnlSampah.setLayout(pnlSampahLayout);
        pnlSampahLayout.setHorizontalGroup(
            pnlSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        pnlSampahLayout.setVerticalGroup(
            pnlSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconSampah.setBackground(new java.awt.Color(255, 255, 255));
        iconSampah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-trash-filled-30.png"))); // NOI18N
        iconSampah.setContentAreaFilled(false);
        iconSampah.setOpaque(true);

        btnSampah.setBackground(new java.awt.Color(255, 255, 255));
        btnSampah.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnSampah.setText("Sampah");
        btnSampah.setContentAreaFilled(false);
        btnSampah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSampah.setOpaque(true);
        btnSampah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSampahMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InformasiAkunLayout = new javax.swing.GroupLayout(InformasiAkun);
        InformasiAkun.setLayout(InformasiAkunLayout);
        InformasiAkunLayout.setHorizontalGroup(
            InformasiAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformasiAkunLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlSampah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(iconSampah, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSampah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        InformasiAkunLayout.setVerticalGroup(
            InformasiAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformasiAkunLayout.createSequentialGroup()
                .addGroup(InformasiAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSampah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconSampah, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnSampah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        Deposit.setBackground(new java.awt.Color(0, 128, 128));

        pnlProduk.setBackground(new java.awt.Color(0, 128, 128));

        javax.swing.GroupLayout pnlProdukLayout = new javax.swing.GroupLayout(pnlProduk);
        pnlProduk.setLayout(pnlProdukLayout);
        pnlProdukLayout.setHorizontalGroup(
            pnlProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        pnlProdukLayout.setVerticalGroup(
            pnlProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconProduk.setBackground(new java.awt.Color(255, 255, 255));
        iconProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-product-filled-30.png"))); // NOI18N
        iconProduk.setContentAreaFilled(false);
        iconProduk.setOpaque(true);

        btnProduk.setBackground(new java.awt.Color(255, 255, 255));
        btnProduk.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnProduk.setText("Produk");
        btnProduk.setContentAreaFilled(false);
        btnProduk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProduk.setOpaque(true);
        btnProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdukMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DepositLayout = new javax.swing.GroupLayout(Deposit);
        Deposit.setLayout(DepositLayout);
        DepositLayout.setHorizontalGroup(
            DepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(iconProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        DepositLayout.setVerticalGroup(
            DepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositLayout.createSequentialGroup()
                .addGroup(DepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconProduk, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnProduk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Beranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BeliSampah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JualProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(InformasiAkun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Deposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Beranda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BeliSampah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JualProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(InformasiAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Deposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu.setBackground(new java.awt.Color(204, 204, 204));
        menu.setLayout(new java.awt.CardLayout());

        beranda.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout berandaLayout = new javax.swing.GroupLayout(beranda);
        beranda.setLayout(berandaLayout);
        berandaLayout.setHorizontalGroup(
            berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
        );
        berandaLayout.setVerticalGroup(
            berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        menu.add(beranda, "beranda");

        verifikasi_setoran.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout verifikasi_setoranLayout = new javax.swing.GroupLayout(verifikasi_setoran);
        verifikasi_setoran.setLayout(verifikasi_setoranLayout);
        verifikasi_setoranLayout.setHorizontalGroup(
            verifikasi_setoranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
        );
        verifikasi_setoranLayout.setVerticalGroup(
            verifikasi_setoranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        menu.add(verifikasi_setoran, "belisampah");

        jualproduk.setBackground(new java.awt.Color(255, 102, 204));

        javax.swing.GroupLayout jualprodukLayout = new javax.swing.GroupLayout(jualproduk);
        jualproduk.setLayout(jualprodukLayout);
        jualprodukLayout.setHorizontalGroup(
            jualprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
        );
        jualprodukLayout.setVerticalGroup(
            jualprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        menu.add(jualproduk, "jualproduk");

        informasiakun.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout informasiakunLayout = new javax.swing.GroupLayout(informasiakun);
        informasiakun.setLayout(informasiakunLayout);
        informasiakunLayout.setHorizontalGroup(
            informasiakunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
        );
        informasiakunLayout.setVerticalGroup(
            informasiakunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        menu.add(informasiakun, "informasiakun");

        deposit.setBackground(new java.awt.Color(0, 255, 51));

        javax.swing.GroupLayout depositLayout = new javax.swing.GroupLayout(deposit);
        deposit.setLayout(depositLayout);
        depositLayout.setHorizontalGroup(
            depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
        );
        depositLayout.setVerticalGroup(
            depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        menu.add(deposit, "deposit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseClicked
        if(Maximize){
            Pegawai.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment max = GraphicsEnvironment.getLocalGraphicsEnvironment();
            Pegawai.this.setMaximizedBounds(max.getMaximumWindowBounds());
            Maximize = false;
        }else{
            setExtendedState(JFrame.NORMAL);
            Maximize = true;
        }
    }//GEN-LAST:event_btnMaximizeMouseClicked

    private void btnMaximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseEntered
        btnMaximize.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_btnMaximizeMouseEntered

    private void btnMaximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseExited
        btnMaximize.setBackground(new Color(0, 128, 128));
    }//GEN-LAST:event_btnMaximizeMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(new Color(232, 15, 35));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new Color(0, 128, 128));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        btnMinimize.setBackground(new Color(0, 128, 128));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        if(Maximize){
            int xMouse = evt.getXOnScreen();
            int yMouse = evt.getYOnScreen();
            this.setLocation(xMouse - x, yMouse - y);
        }

    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void btnBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseClicked
        btnBeranda.setBackground(new Color(0, 128, 128));
        btnBeranda.setForeground(new Color(255, 255, 255));
        iconBeranda.setBackground(new Color(0, 128, 128));
        pnlBeranda.setBackground(new Color(255, 255, 255));
        iconBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30(1).png")));
        title.setText("Beranda - Basara 1.0");
        cardlayout.show(menu, "beranda");
        
        
        btnVerSetoran.setBackground(new Color(255, 255, 255));
        btnVerSetoran.setForeground(new Color(0, 0, 0));
        iconVerSetoran.setBackground(new Color(255, 255, 255));
        pnlVerSetoran.setBackground(new Color(0, 128, 128));
        iconVerSetoran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-checklist-filled-30.png")));
        
        btnVerPengrajin.setBackground(new Color(255, 255, 255));
        btnVerPengrajin.setForeground(new Color(0, 0, 0));
        iconVerPengrajin.setBackground(new Color(255, 255, 255));
        pnlVerPengrajin.setBackground(new Color(0, 128, 128));
        iconVerPengrajin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-todo-list-filled-30.png")));
        
        btnSampah.setBackground(new Color(255, 255, 255));
        btnSampah.setForeground(new Color(0, 0, 0));
        iconSampah.setBackground(new Color(255, 255, 255));
        pnlSampah.setBackground(new Color(0, 128, 128));
        iconSampah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-trash-filled-30.png")));
        
        btnProduk.setBackground(new Color(255, 255, 255));
        btnProduk.setForeground(new Color(0, 0, 0));
        iconProduk.setBackground(new Color(255, 255, 255));
        pnlProduk.setBackground(new Color(0, 128, 128));
        iconProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-product-filled-30.png")));
    }//GEN-LAST:event_btnBerandaMouseClicked

    private void iconBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconBerandaMouseClicked
//        ImageIcon ico = new ImageIcon("src\images\icons8-home-30(1)");
//        iconBeranda
    }//GEN-LAST:event_iconBerandaMouseClicked

    private void btnBerandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseEntered

    }//GEN-LAST:event_btnBerandaMouseEntered

    private void btnBerandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseExited

    }//GEN-LAST:event_btnBerandaMouseExited

    private void btnBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerandaActionPerformed

    }//GEN-LAST:event_btnBerandaActionPerformed

    private void btnVerSetoranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerSetoranMouseClicked
        btnBeranda.setBackground(new Color(255, 255, 255));
        btnBeranda.setForeground(new Color(0, 0, 0));
        iconBeranda.setBackground(new Color(255, 255, 255));
        pnlBeranda.setBackground(new Color(0, 128, 128));
        iconBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png")));
        
        btnVerSetoran.setBackground(new Color(0, 128, 128));
        btnVerSetoran.setForeground(new Color(255, 255, 255));
        iconVerSetoran.setBackground(new Color(0, 128, 128));
        pnlVerSetoran.setBackground(new Color(255, 255, 255));
        iconVerSetoran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-checklist-filled-30 (1).png")));
        cardlayout.show(menu, "belisampah");
        title.setText("Verifikasi Setoran - Basara 1.0");
        
        btnVerPengrajin.setBackground(new Color(255, 255, 255));
        btnVerPengrajin.setForeground(new Color(0, 0, 0));
        iconVerPengrajin.setBackground(new Color(255, 255, 255));
        pnlVerPengrajin.setBackground(new Color(0, 128, 128));
        iconVerPengrajin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-todo-list-filled-30.png")));
        
        btnSampah.setBackground(new Color(255, 255, 255));
        btnSampah.setForeground(new Color(0, 0, 0));
        iconSampah.setBackground(new Color(255, 255, 255));
        pnlSampah.setBackground(new Color(0, 128, 128));
        iconSampah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-trash-filled-30.png")));
        
        btnProduk.setBackground(new Color(255, 255, 255));
        btnProduk.setForeground(new Color(0, 0, 0));
        iconProduk.setBackground(new Color(255, 255, 255));
        pnlProduk.setBackground(new Color(0, 128, 128));
        iconProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-product-filled-30.png")));
    }//GEN-LAST:event_btnVerSetoranMouseClicked

    private void btnVerPengrajinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerPengrajinMouseClicked
        btnBeranda.setBackground(new Color(255, 255, 255));
        btnBeranda.setForeground(new Color(0, 0, 0));
        iconBeranda.setBackground(new Color(255, 255, 255));
        pnlBeranda.setBackground(new Color(0, 128, 128));
        iconBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png")));
        
        btnVerSetoran.setBackground(new Color(255, 255, 255));
        btnVerSetoran.setForeground(new Color(0, 0, 0));
        iconVerSetoran.setBackground(new Color(255, 255, 255));
        pnlVerSetoran.setBackground(new Color(0, 128, 128));
        iconVerSetoran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-checklist-filled-30.png")));
        
        btnVerPengrajin.setBackground(new Color(0, 128, 128));
        btnVerPengrajin.setForeground(new Color(255, 255, 255));
        iconVerPengrajin.setBackground(new Color(0, 128, 128));
        pnlVerPengrajin.setBackground(new Color(255, 255, 255));
        iconVerPengrajin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-todo-list-filled-30 (1).png")));
        cardlayout.show(menu, "jualproduk");
        title.setText("Verifikasi Pengrajin - Basara 1.0");
        
        btnSampah.setBackground(new Color(255, 255, 255));
        btnSampah.setForeground(new Color(0, 0, 0));
        iconSampah.setBackground(new Color(255, 255, 255));
        pnlSampah.setBackground(new Color(0, 128, 128));
        iconSampah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-trash-filled-30.png")));
        
        btnProduk.setBackground(new Color(255, 255, 255));
        btnProduk.setForeground(new Color(0, 0, 0));
        iconProduk.setBackground(new Color(255, 255, 255));
        pnlProduk.setBackground(new Color(0, 128, 128));
        iconProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-product-filled-30.png")));
    }//GEN-LAST:event_btnVerPengrajinMouseClicked

    private void btnSampahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSampahMouseClicked
        btnBeranda.setBackground(new Color(255, 255, 255));
        btnBeranda.setForeground(new Color(0, 0, 0));
        iconBeranda.setBackground(new Color(255, 255, 255));
        pnlBeranda.setBackground(new Color(0, 128, 128));
        iconBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png")));
        
        btnVerSetoran.setBackground(new Color(255, 255, 255));
        btnVerSetoran.setForeground(new Color(0, 0, 0));
        iconVerSetoran.setBackground(new Color(255, 255, 255));
        pnlVerSetoran.setBackground(new Color(0, 128, 128));
        iconVerSetoran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-checklist-filled-30.png")));
        
        btnVerPengrajin.setBackground(new Color(255, 255, 255));
        btnVerPengrajin.setForeground(new Color(0, 0, 0));
        iconVerPengrajin.setBackground(new Color(255, 255, 255));
        pnlVerPengrajin.setBackground(new Color(0, 128, 128));
        iconVerPengrajin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-todo-list-filled-30.png")));
        
        btnSampah.setBackground(new Color(0, 128, 128));
        btnSampah.setForeground(new Color(255, 255, 255));
        iconSampah.setBackground(new Color(0, 128, 128));
        pnlSampah.setBackground(new Color(255, 255, 255));
        iconSampah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-trash-filled-30 (1).png")));
        cardlayout.show(menu, "informasiakun");
        title.setText("Sampah - Basara 1.0");
        
        btnProduk.setBackground(new Color(255, 255, 255));
        btnProduk.setForeground(new Color(0, 0, 0));
        iconProduk.setBackground(new Color(255, 255, 255));
        pnlProduk.setBackground(new Color(0, 128, 128));
        iconProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-product-filled-30.png")));
    }//GEN-LAST:event_btnSampahMouseClicked

    private void btnProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdukMouseClicked
        btnBeranda.setBackground(new Color(255, 255, 255));
        btnBeranda.setForeground(new Color(0, 0, 0));
        iconBeranda.setBackground(new Color(255, 255, 255));
        pnlBeranda.setBackground(new Color(0, 128, 128));
        iconBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png")));
        
        btnVerSetoran.setBackground(new Color(255, 255, 255));
        btnVerSetoran.setForeground(new Color(0, 0, 0));
        iconVerSetoran.setBackground(new Color(255, 255, 255));
        pnlVerSetoran.setBackground(new Color(0, 128, 128));
        iconVerSetoran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-checklist-filled-30.png")));
        
        btnVerPengrajin.setBackground(new Color(255, 255, 255));
        btnVerPengrajin.setForeground(new Color(0, 0, 0));
        iconVerPengrajin.setBackground(new Color(255, 255, 255));
        pnlVerPengrajin.setBackground(new Color(0, 128, 128));
        iconVerPengrajin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-todo-list-filled-30.png")));
        
        btnSampah.setBackground(new Color(255, 255, 255));
        btnSampah.setForeground(new Color(0, 0, 0));
        iconSampah.setBackground(new Color(255, 255, 255));
        pnlSampah.setBackground(new Color(0, 128, 128));
        iconSampah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-trash-filled-30.png")));
        
        btnProduk.setBackground(new Color(0, 128, 128));
        btnProduk.setForeground(new Color(255, 255, 255));
        iconProduk.setBackground(new Color (0, 128, 128));
        pnlProduk.setBackground(new Color(255, 255, 255));
        iconProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-product-filled-30 (1).png")));
        cardlayout.show(menu, "deposit");
        title.setText("Produk - Basara 1.0");
    }//GEN-LAST:event_btnProdukMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BeliSampah;
    private javax.swing.JPanel Beranda;
    private javax.swing.JPanel Deposit;
    private javax.swing.JPanel InformasiAkun;
    private javax.swing.JPanel JualProduk;
    private javax.swing.JPanel beranda;
    private javax.swing.JButton btnBeranda;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMaximize;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnProduk;
    private javax.swing.JButton btnSampah;
    private javax.swing.JButton btnVerPengrajin;
    private javax.swing.JButton btnVerSetoran;
    private javax.swing.JPanel deposit;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header2;
    private javax.swing.JButton iconBeranda;
    private javax.swing.JButton iconProduk;
    private javax.swing.JButton iconSampah;
    private javax.swing.JButton iconVerPengrajin;
    private javax.swing.JButton iconVerSetoran;
    private javax.swing.JPanel informasiakun;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jualproduk;
    private javax.swing.JLabel lb_date;
    private javax.swing.JLabel lb_time;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel pnlBeranda;
    private javax.swing.JPanel pnlProduk;
    private javax.swing.JPanel pnlSampah;
    private javax.swing.JPanel pnlVerPengrajin;
    private javax.swing.JPanel pnlVerSetoran;
    private javax.swing.JLabel title;
    private javax.swing.JPanel verifikasi_setoran;
    // End of variables declaration//GEN-END:variables
}
