/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.basara.view;

import id.basara.controller.AtributController;
import id.basara.controller.ClockController;
import id.basara.controller.ProductController;
import id.basara.controller.SampahController;
import id.basara.controller.TransaksiController;
import id.basara.model.Produk;
import id.basara.model.Sampah;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.*;
import java.sql.*;
import java.util.Observable;
import java.util.Observer;
import javax.imageio.ImageIO;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author HEWLETT-PACKARD
 */
public class Pengrajin extends javax.swing.JFrame implements Observer {
    
    /**
     * Creates new form Pengguna
     */
    
    private TransaksiController transaksiController = new TransaksiController();
    private SampahController sampahController = new SampahController();
    private AtributController atributController = new AtributController();
    private ClockController jam = new ClockController();
    private ProductController produk = new ProductController();
    
    public static BufferedImage gambar_c = null;
    String Username;
    String path;
    Image images;
    byte[] bitarray=null;
    static boolean Maximize = true;
    int x, y;

    CardLayout cardlayout;
    
    
    public Pengrajin() {
        initComponents();
        cardlayout = (CardLayout) menu.getLayout();
        ambil_gambar(show_image);
        
    }
    
     public Pengrajin(String Username) {
         this.Username=Username;
        initComponents();
        cardlayout = (CardLayout) menu.getLayout();
        ambil_gambar(show_image);
        
    }
    
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        btnMaximize = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        header2 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lb_time = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        Beranda = new javax.swing.JPanel();
        pnlBeranda = new javax.swing.JPanel();
        iconBeranda = new javax.swing.JButton();
        btnBeranda = new javax.swing.JButton();
        BeliSampah = new javax.swing.JPanel();
        pnlBeliSampah = new javax.swing.JPanel();
        iconBeliSampah = new javax.swing.JButton();
        btnBeliSampah = new javax.swing.JButton();
        JualProduk = new javax.swing.JPanel();
        pnlJualProduk = new javax.swing.JPanel();
        iconJualProduk = new javax.swing.JButton();
        btnJualProduk = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        beranda = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        beli_sampah = new javax.swing.JPanel();
        bt_belisampah = new javax.swing.JButton();
        lb_ktgbelisampah = new javax.swing.JLabel();
        bt_hitungbelisampah = new javax.swing.JButton();
        cb_ktgbelisampah = new javax.swing.JComboBox();
        cb_namabelisampah = new javax.swing.JComboBox();
        lb_namabelisampah = new javax.swing.JLabel();
        lb_hargabelisampah = new javax.swing.JLabel();
        lb_genhargabelisampah = new javax.swing.JLabel();
        tf_jumlahbelisampah = new javax.swing.JTextField();
        lb_jumlahbelisampah = new javax.swing.JLabel();
        lb_totalbelisampah = new javax.swing.JLabel();
        lb_gentotalbelisampah = new javax.swing.JLabel();
        lb_belanjasampah = new javax.swing.JLabel();
        jual_produk = new javax.swing.JPanel();
        show_image = new javax.swing.JLabel();
        lb_belanjasampah1 = new javax.swing.JLabel();
        lb_ktgbelisampah1 = new javax.swing.JLabel();
        lb_ktgbelisampah2 = new javax.swing.JLabel();
        lb_ktgbelisampah3 = new javax.swing.JLabel();
        lb_ktgbelisampah4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        save = new javax.swing.JButton();
        judul = new javax.swing.JTextField();
        kategori = new javax.swing.JTextField();
        namaproduk = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jumlahstok = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 720));

        header.setBackground(new java.awt.Color(0, 128, 128));
        header.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 128, 128)));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnMaximize.setBackground(new java.awt.Color(0, 128, 128));
        btnMaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/max.png"))); // NOI18N
        btnMaximize.setContentAreaFilled(false);
        btnMaximize.setOpaque(true);
        btnMaximize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/max.png"))); // NOI18N
        btnMaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseExited(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(0, 128, 128));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnExit.setContentAreaFilled(false);
        btnExit.setOpaque(true);
        btnExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        btnMinimize.setBackground(new java.awt.Color(0, 128, 128));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/min.png"))); // NOI18N
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setOpaque(true);
        btnMinimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/min.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });

        title.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Beranda - Basara 1.0");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMaximize, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
            .addComponent(btnMaximize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        header2.setBackground(new java.awt.Color(255, 255, 255));
        header2.setForeground(new java.awt.Color(0, 128, 128));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-40.png"))); // NOI18N
        jButton11.setContentAreaFilled(false);

        jButton12.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton12.setText("Nama Pengrajin");
        jButton12.setContentAreaFilled(false);
        jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-exit-20.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Logout");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/basara.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Helo,");

        lb_time.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lb_date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout header2Layout = new javax.swing.GroupLayout(header2);
        header2.setLayout(header2Layout);
        header2Layout.setHorizontalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header2Layout.createSequentialGroup()
                        .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        header2Layout.setVerticalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(header2Layout.createSequentialGroup()
                .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(header2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lb_time, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(header2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(header2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panel.setBackground(new java.awt.Color(255, 255, 255));

        Beranda.setBackground(new java.awt.Color(0, 128, 128));

        pnlBeranda.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlBerandaLayout = new javax.swing.GroupLayout(pnlBeranda);
        pnlBeranda.setLayout(pnlBerandaLayout);
        pnlBerandaLayout.setHorizontalGroup(
            pnlBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        pnlBerandaLayout.setVerticalGroup(
            pnlBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconBeranda.setBackground(new java.awt.Color(0, 128, 128));
        iconBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30(1).png"))); // NOI18N
        iconBeranda.setContentAreaFilled(false);
        iconBeranda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iconBeranda.setOpaque(true);
        iconBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconBerandaMouseClicked(evt);
            }
        });

        btnBeranda.setBackground(new java.awt.Color(0, 128, 128));
        btnBeranda.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnBeranda.setForeground(new java.awt.Color(255, 255, 255));
        btnBeranda.setText("Beranda");
        btnBeranda.setContentAreaFilled(false);
        btnBeranda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBeranda.setOpaque(true);
        btnBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBerandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBerandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBerandaMouseExited(evt);
            }
        });
        btnBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BerandaLayout = new javax.swing.GroupLayout(Beranda);
        Beranda.setLayout(BerandaLayout);
        BerandaLayout.setHorizontalGroup(
            BerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BerandaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(iconBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        BerandaLayout.setVerticalGroup(
            BerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BerandaLayout.createSequentialGroup()
                .addGroup(BerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnBeranda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        BeliSampah.setBackground(new java.awt.Color(0, 128, 128));

        pnlBeliSampah.setBackground(new java.awt.Color(0, 128, 128));

        javax.swing.GroupLayout pnlBeliSampahLayout = new javax.swing.GroupLayout(pnlBeliSampah);
        pnlBeliSampah.setLayout(pnlBeliSampahLayout);
        pnlBeliSampahLayout.setHorizontalGroup(
            pnlBeliSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        pnlBeliSampahLayout.setVerticalGroup(
            pnlBeliSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconBeliSampah.setBackground(new java.awt.Color(255, 255, 255));
        iconBeliSampah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-buying-30.png"))); // NOI18N
        iconBeliSampah.setContentAreaFilled(false);
        iconBeliSampah.setOpaque(true);

        btnBeliSampah.setBackground(new java.awt.Color(255, 255, 255));
        btnBeliSampah.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnBeliSampah.setText("Beli Sampah");
        btnBeliSampah.setContentAreaFilled(false);
        btnBeliSampah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBeliSampah.setOpaque(true);
        btnBeliSampah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBeliSampahMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BeliSampahLayout = new javax.swing.GroupLayout(BeliSampah);
        BeliSampah.setLayout(BeliSampahLayout);
        BeliSampahLayout.setHorizontalGroup(
            BeliSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BeliSampahLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlBeliSampah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(iconBeliSampah, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBeliSampah, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        BeliSampahLayout.setVerticalGroup(
            BeliSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BeliSampahLayout.createSequentialGroup()
                .addGroup(BeliSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBeliSampah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconBeliSampah, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnBeliSampah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        JualProduk.setBackground(new java.awt.Color(0, 128, 128));

        pnlJualProduk.setBackground(new java.awt.Color(0, 128, 128));

        javax.swing.GroupLayout pnlJualProdukLayout = new javax.swing.GroupLayout(pnlJualProduk);
        pnlJualProduk.setLayout(pnlJualProdukLayout);
        pnlJualProdukLayout.setHorizontalGroup(
            pnlJualProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        pnlJualProdukLayout.setVerticalGroup(
            pnlJualProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconJualProduk.setBackground(new java.awt.Color(255, 255, 255));
        iconJualProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sell-filled-30.png"))); // NOI18N
        iconJualProduk.setContentAreaFilled(false);
        iconJualProduk.setOpaque(true);

        btnJualProduk.setBackground(new java.awt.Color(255, 255, 255));
        btnJualProduk.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnJualProduk.setText("Jual Produk");
        btnJualProduk.setContentAreaFilled(false);
        btnJualProduk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnJualProduk.setOpaque(true);
        btnJualProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJualProdukMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JualProdukLayout = new javax.swing.GroupLayout(JualProduk);
        JualProduk.setLayout(JualProdukLayout);
        JualProdukLayout.setHorizontalGroup(
            JualProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JualProdukLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlJualProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(iconJualProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnJualProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        JualProdukLayout.setVerticalGroup(
            JualProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JualProdukLayout.createSequentialGroup()
                .addGroup(JualProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlJualProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconJualProduk, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnJualProduk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Beranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BeliSampah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JualProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Beranda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BeliSampah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JualProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu.setBackground(new java.awt.Color(204, 204, 204));
        menu.setLayout(new java.awt.CardLayout());

        beranda.setBackground(new java.awt.Color(255, 255, 255));
        beranda.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 128, 128)));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Nama Lengkap");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Username");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("No Rekening");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("Saldo");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        javax.swing.GroupLayout berandaLayout = new javax.swing.GroupLayout(beranda);
        beranda.setLayout(berandaLayout);
        berandaLayout.setHorizontalGroup(
            berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(berandaLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addGroup(berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addGroup(berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(284, 284, 284))
        );
        berandaLayout.setVerticalGroup(
            berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(berandaLayout.createSequentialGroup()
                .addGroup(berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(berandaLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(berandaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(230, 230, 230))
        );

        menu.add(beranda, "beranda");

        beli_sampah.setBackground(new java.awt.Color(255, 255, 255));

        bt_belisampah.setText("Belanja");
        bt_belisampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_belisampahActionPerformed(evt);
            }
        });

        lb_ktgbelisampah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_ktgbelisampah.setText("Kategori");

        bt_hitungbelisampah.setText("Hitung");
        bt_hitungbelisampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hitungbelisampahActionPerformed(evt);
            }
        });

        cb_ktgbelisampah.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_ktgbelisampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ktgbelisampahActionPerformed(evt);
            }
        });

        cb_namabelisampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_namabelisampahActionPerformed(evt);
            }
        });

        lb_namabelisampah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_namabelisampah.setText("Nama Sampah");

        lb_hargabelisampah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_hargabelisampah.setText("Harga");

        lb_genhargabelisampah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lb_jumlahbelisampah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_jumlahbelisampah.setText("Jumlah");

        lb_totalbelisampah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_totalbelisampah.setText("Total");

        lb_gentotalbelisampah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lb_belanjasampah.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lb_belanjasampah.setText("BELANJA");

        javax.swing.GroupLayout beli_sampahLayout = new javax.swing.GroupLayout(beli_sampah);
        beli_sampah.setLayout(beli_sampahLayout);
        beli_sampahLayout.setHorizontalGroup(
            beli_sampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beli_sampahLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(beli_sampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(beli_sampahLayout.createSequentialGroup()
                        .addComponent(bt_belisampah)
                        .addGap(18, 18, 18)
                        .addComponent(bt_hitungbelisampah))
                    .addComponent(lb_totalbelisampah, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(beli_sampahLayout.createSequentialGroup()
                        .addGroup(beli_sampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_namabelisampah, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_hargabelisampah, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_ktgbelisampah, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_jumlahbelisampah, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(beli_sampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_ktgbelisampah, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_genhargabelisampah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_namabelisampah, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_gentotalbelisampah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_jumlahbelisampah, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(559, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, beli_sampahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_belanjasampah)
                .addGap(444, 444, 444))
        );
        beli_sampahLayout.setVerticalGroup(
            beli_sampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beli_sampahLayout.createSequentialGroup()
                .addComponent(lb_belanjasampah, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(beli_sampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_ktgbelisampah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_ktgbelisampah))
                .addGap(22, 22, 22)
                .addGroup(beli_sampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_namabelisampah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_namabelisampah))
                .addGap(32, 32, 32)
                .addGroup(beli_sampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_genhargabelisampah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_hargabelisampah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(beli_sampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_jumlahbelisampah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_jumlahbelisampah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(beli_sampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_totalbelisampah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_gentotalbelisampah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(beli_sampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_belisampah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hitungbelisampah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );

        menu.add(beli_sampah, "beli_sampah");

        jual_produk.setBackground(new java.awt.Color(255, 255, 255));

        show_image.setPreferredSize(new java.awt.Dimension(300, 300));

        lb_belanjasampah1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lb_belanjasampah1.setText("JUAL PRODUK");

        lb_ktgbelisampah1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_ktgbelisampah1.setText("Kategori");

        lb_ktgbelisampah2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_ktgbelisampah2.setText("Jumlah Stok");

        lb_ktgbelisampah3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_ktgbelisampah3.setText("Nama Produk");

        lb_ktgbelisampah4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_ktgbelisampah4.setText("Harga");

        jButton3.setText("Choose");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jual_produkLayout = new javax.swing.GroupLayout(jual_produk);
        jual_produk.setLayout(jual_produkLayout);
        jual_produkLayout.setHorizontalGroup(
            jual_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jual_produkLayout.createSequentialGroup()
                .addGap(433, 433, 433)
                .addComponent(lb_belanjasampah1))
            .addGroup(jual_produkLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jual_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_ktgbelisampah1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ktgbelisampah3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ktgbelisampah4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ktgbelisampah2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(jual_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jual_produkLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jumlahstok, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138)
                .addComponent(show_image, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jual_produkLayout.createSequentialGroup()
                .addGap(607, 607, 607)
                .addComponent(save)
                .addGap(54, 54, 54)
                .addComponent(jButton3)
                .addGap(28, 28, 28)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jual_produkLayout.setVerticalGroup(
            jual_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jual_produkLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lb_belanjasampah1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jual_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jual_produkLayout.createSequentialGroup()
                        .addComponent(lb_ktgbelisampah1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lb_ktgbelisampah3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(lb_ktgbelisampah4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(lb_ktgbelisampah2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jual_produkLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(namaproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jumlahstok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(show_image, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jual_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jual_produkLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jual_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(save)
                            .addComponent(jButton3)))))
        );

        menu.add(jual_produk, "jual_produk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseClicked
        if(Maximize){
            Pengrajin.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment max = GraphicsEnvironment.getLocalGraphicsEnvironment();
            Pengrajin.this.setMaximizedBounds(max.getMaximumWindowBounds());
            Maximize = false;
        }else{
            setExtendedState(JFrame.NORMAL);
            Maximize = true;
        }
    }//GEN-LAST:event_btnMaximizeMouseClicked

    private void btnMaximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseEntered
        btnMaximize.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_btnMaximizeMouseEntered

    private void btnMaximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseExited
        btnMaximize.setBackground(new Color(0, 128, 128));
    }//GEN-LAST:event_btnMaximizeMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(new Color(232, 15, 35));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new Color(0, 128, 128));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        btnMinimize.setBackground(new Color(0, 128, 128));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        if(Maximize){
            int xMouse = evt.getXOnScreen();
            int yMouse = evt.getYOnScreen();
            this.setLocation(xMouse - x, yMouse - y);
        }

    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void btnBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseClicked
        btnBeranda.setBackground(new Color(0, 128, 128));
        btnBeranda.setForeground(new Color(255, 255, 255));
        iconBeranda.setBackground(new Color(0, 128, 128));
        pnlBeranda.setBackground(new Color(255, 255, 255));
        iconBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30(1).png")));
        title.setText("Beranda - Basara 1.0");
        cardlayout.show(menu, "beranda");
        
        
        btnBeliSampah.setBackground(new Color(255, 255, 255));
        btnBeliSampah.setForeground(new Color(0, 0, 0));
        iconBeliSampah.setBackground(new Color(255, 255, 255));
        pnlBeliSampah.setBackground(new Color(0, 128, 128));
        iconBeliSampah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-buying-30.png")));
        
        btnJualProduk.setBackground(new Color(255, 255, 255));
        btnJualProduk.setForeground(new Color(0, 0, 0));
        iconJualProduk.setBackground(new Color(255, 255, 255));
        pnlJualProduk.setBackground(new Color(0, 128, 128));
        iconJualProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sell-filled-30.png")));
        
        
    }//GEN-LAST:event_btnBerandaMouseClicked

    private void iconBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconBerandaMouseClicked
//        ImageIcon ico = new ImageIcon("src\images\icons8-home-30(1)");
//        iconBeranda
    }//GEN-LAST:event_iconBerandaMouseClicked

    private void btnBerandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseEntered

    }//GEN-LAST:event_btnBerandaMouseEntered

    private void btnBerandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseExited

    }//GEN-LAST:event_btnBerandaMouseExited

    private void btnBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerandaActionPerformed

    }//GEN-LAST:event_btnBerandaActionPerformed

    private void btnBeliSampahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeliSampahMouseClicked
        btnBeranda.setBackground(new Color(255, 255, 255));
        btnBeranda.setForeground(new Color(0, 0, 0));
        iconBeranda.setBackground(new Color(255, 255, 255));
        pnlBeranda.setBackground(new Color(0, 128, 128));
        iconBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png")));
        
        btnBeliSampah.setBackground(new Color(0, 128, 128));
        btnBeliSampah.setForeground(new Color(255, 255, 255));
        iconBeliSampah.setBackground(new Color(0, 128, 128));
        pnlBeliSampah.setBackground(new Color(255, 255, 255));
        iconBeliSampah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-buying-30 (1).png")));
        cardlayout.show(menu, "beli_sampah");
        title.setText("Beli Sampah - Basara 1.0");
        
        btnJualProduk.setBackground(new Color(255, 255, 255));
        btnJualProduk.setForeground(new Color(0, 0, 0));
        iconJualProduk.setBackground(new Color(255, 255, 255));
        pnlJualProduk.setBackground(new Color(0, 128, 128));
        iconJualProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sell-filled-30.png")));
        
        
    }//GEN-LAST:event_btnBeliSampahMouseClicked

    private void btnJualProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJualProdukMouseClicked
        btnBeranda.setBackground(new Color(255, 255, 255));
        btnBeranda.setForeground(new Color(0, 0, 0));
        iconBeranda.setBackground(new Color(255, 255, 255));
        pnlBeranda.setBackground(new Color(0, 128, 128));
        iconBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png")));
        
        btnBeliSampah.setBackground(new Color(255, 255, 255));
        btnBeliSampah.setForeground(new Color(0, 0, 0));
        iconBeliSampah.setBackground(new Color(255, 255, 255));
        pnlBeliSampah.setBackground(new Color(0, 128, 128));
        iconBeliSampah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-buying-30.png")));
        
        btnJualProduk.setBackground(new Color(0, 128, 128));
        btnJualProduk.setForeground(new Color(255, 255, 255));
        iconJualProduk.setBackground(new Color(0, 128, 128));
        pnlJualProduk.setBackground(new Color(255, 255, 255));
        iconJualProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sell-filled-30 (1).png")));
        cardlayout.show(menu, "jual_produk");
        title.setText("Jual Produk - Basara 1.0");
        
       
    }//GEN-LAST:event_btnJualProdukMouseClicked

    private void bt_belisampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_belisampahActionPerformed
        
    }//GEN-LAST:event_bt_belisampahActionPerformed

    private void bt_hitungbelisampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hitungbelisampahActionPerformed
        
    }//GEN-LAST:event_bt_hitungbelisampahActionPerformed

    private void cb_ktgbelisampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ktgbelisampahActionPerformed
       
    }//GEN-LAST:event_cb_ktgbelisampahActionPerformed

    private void cb_namabelisampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_namabelisampahActionPerformed
        
    }//GEN-LAST:event_cb_namabelisampahActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     JFileChooser chooser = new JFileChooser(System.getProperty("user.home"));
     chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
     chooser.setFileFilter(new FileNameExtensionFilter("jpg|png|bmp","jpg","png","bmp"));
     if(chooser.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
         File file=chooser.getSelectedFile();
         try{
             if(file.length()>205659){
                 JOptionPane.showMessageDialog(rootPane, "Gambar Terlalu Besar","Max 200KB", JOptionPane.WARNING_MESSAGE);
             }else{
                 BufferedImage loadImg = loadImage(file.toString());
          
                 gambar_c = resize(loadImg,300,300);
                 ImageIcon imageicon = new ImageIcon(gambar_c);
                    show_image.setIcon(imageicon);
                 path = file.getAbsolutePath();
             }
         }catch (Exception e){
             
         }
         judul.setText(file.getName());
     }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
    try{
        Produk p = new Produk();
        p.setNama(namaproduk.getText());
        p.setKategori(kategori.getText());
        p.setHarga_jual(harga.getText());
        p.setHarga_beli(harga.getText());
        p.setKode_produk("pD001");
        p.setUsername_pengrajin(Username);
        p.setJumlah_stok(jumlahstok.getText());
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        File img=new File(path);
        FileInputStream input = new FileInputStream(img);
        
        try{
            byte[] buf = new byte[1024];
            for(int readbyte;(readbyte=input.read(buf))!=-1;){
                output.write(buf,0,readbyte);
            }
            bitarray=output.toByteArray();
            p.setProduk_gambar(bitarray);
            produk.insert(p, "Produk");
            
            JOptionPane.showMessageDialog(this, "Produk berhasil ditambahkan");
            
        } catch (Exception e){
            
        }
        
    }catch (Exception e){
        
    } 
        
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengrajin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengrajin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengrajin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengrajin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengrajin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BeliSampah;
    private javax.swing.JPanel Beranda;
    private javax.swing.JPanel JualProduk;
    private javax.swing.JPanel beli_sampah;
    private javax.swing.JPanel beranda;
    private javax.swing.JButton bt_belisampah;
    private javax.swing.JButton bt_hitungbelisampah;
    private javax.swing.JButton btnBeliSampah;
    private javax.swing.JButton btnBeranda;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnJualProduk;
    private javax.swing.JButton btnMaximize;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JComboBox cb_ktgbelisampah;
    private javax.swing.JComboBox cb_namabelisampah;
    private javax.swing.JTextField harga;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header2;
    private javax.swing.JButton iconBeliSampah;
    private javax.swing.JButton iconBeranda;
    private javax.swing.JButton iconJualProduk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jual_produk;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField jumlahstok;
    private javax.swing.JTextField kategori;
    private javax.swing.JLabel lb_belanjasampah;
    private javax.swing.JLabel lb_belanjasampah1;
    private javax.swing.JLabel lb_date;
    private javax.swing.JLabel lb_genhargabelisampah;
    private javax.swing.JLabel lb_gentotalbelisampah;
    private javax.swing.JLabel lb_hargabelisampah;
    private javax.swing.JLabel lb_jumlahbelisampah;
    private javax.swing.JLabel lb_ktgbelisampah;
    private javax.swing.JLabel lb_ktgbelisampah1;
    private javax.swing.JLabel lb_ktgbelisampah2;
    private javax.swing.JLabel lb_ktgbelisampah3;
    private javax.swing.JLabel lb_ktgbelisampah4;
    private javax.swing.JLabel lb_namabelisampah;
    private javax.swing.JLabel lb_time;
    private javax.swing.JLabel lb_totalbelisampah;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField namaproduk;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel pnlBeliSampah;
    private javax.swing.JPanel pnlBeranda;
    private javax.swing.JPanel pnlJualProduk;
    private javax.swing.JButton save;
    private javax.swing.JLabel show_image;
    private javax.swing.JTextField tf_jumlahbelisampah;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

       public static BufferedImage resize(BufferedImage img, int newW, int newH ){
        int w = img.getWidth();
        int h = img.getHeight();
        BufferedImage dimg = dimg = new BufferedImage(newW, newH, img.getType());
        Graphics2D g = dimg.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g.drawImage(img,0,0,newW,newH,0,0,w,h,null);
        
        g.dispose();
        return dimg;
    }
    
    public static BufferedImage loadImage(String alamat) {
        BufferedImage bi = null;
        try {
            bi = ImageIO.read(new File(alamat));
        }catch (Exception e){
            e.printStackTrace();
        }
        return bi;
    }
    
    public void ambil_gambar(javax.swing.JLabel label_gambar){
        try{
            byte[] img = sampahController.getgambar("sampah_gambar", "sampah" , "kode_sampah='111'");
            BufferedImage file = ImageIO.read(new ByteArrayInputStream(img));
            gambar_c = resize(file,300,300);
            ImageIcon icon = new ImageIcon(gambar_c);
            label_gambar.setIcon(icon);
        }catch (Exception e){
            
        }
    }
    
    @Override
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
