/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.basara.view;

import id.basara.controller.AtributController;
import id.basara.controller.TransaksiController;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.util.Observable;
import java.util.Observer;
import id.basara.database.DatabaseMySQL;
import id.basara.model.Atribut;
import java.util.Calendar;
import java.util.GregorianCalendar;
import id.basara.controller.ClockController;
import id.basara.model.CrudState;
import id.basara.model.Transaksi;
/**
 *
 * @author HEWLETT-PACKARD
 */
public class Pengguna extends javax.swing.JFrame implements Observer {

    private TransaksiController transaksiController = new TransaksiController();
    private AtributController atributController = new AtributController();
    private ClockController jam = new ClockController();
    
    
    /**
     * Creates new form Pengguna
     */
    static boolean Maximize = true;
    int x, y;
    
    
    CardLayout cardlayout;
    public Pengguna() {
        
        initComponents();
        jam.clock(lb_date, lb_time);
        cardlayout = (CardLayout) (menu.getLayout());
        transaksiController.addObserver(this);
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        transaksiController.addObserver(this);
        setAtribut(atributController.getAllData("kategori","sampah"),cb_ktgsampah);
        setAtribut(atributController.getAllData("kategori","produk"),cb_ktgproduk);
        
        //setTransaksiTable(TransaksiController.getAllProduct());
        
        if (!DatabaseMySQL.isConnect()){
            System.exit(0);
        }
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        btnMaximize = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        header2 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlBeranda = new javax.swing.JPanel();
        iconBeranda = new javax.swing.JButton();
        btnBeranda = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        pnlSetor = new javax.swing.JPanel();
        iconSetor = new javax.swing.JButton();
        btnSetor = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        pnlBelanja = new javax.swing.JPanel();
        iconBelanja = new javax.swing.JButton();
        btnBelanja = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        pnlRekening = new javax.swing.JPanel();
        iconRekening = new javax.swing.JButton();
        btnRekening = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        pnlRiwayat = new javax.swing.JPanel();
        iconRiwayat = new javax.swing.JButton();
        btnRiwayat = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        beranda1 = new javax.swing.JPanel();
        setor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lb_namasampah = new javax.swing.JLabel();
        lb_ktgsampah = new javax.swing.JLabel();
        lb_jumlah = new javax.swing.JLabel();
        bt_Setor = new javax.swing.JButton();
        cb_namasampah = new javax.swing.JComboBox();
        cb_ktgsampah = new javax.swing.JComboBox();
        lb_hargasampah = new javax.swing.JLabel();
        lb_genhargasampah = new javax.swing.JLabel();
        lb_total1 = new javax.swing.JLabel();
        lb_gentotal = new javax.swing.JLabel();
        tf_jumlah = new javax.swing.JTextField();
        bt_hitung = new javax.swing.JButton();
        lb_genhargasampah1 = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        lb_time = new javax.swing.JLabel();
        belanja = new javax.swing.JPanel();
        lb_ktgproduk = new javax.swing.JLabel();
        cb_ktgproduk = new javax.swing.JComboBox();
        cb_namaproduk = new javax.swing.JComboBox();
        lb_namasampah1 = new javax.swing.JLabel();
        lb_hargaproduk = new javax.swing.JLabel();
        lb_genhargaproduk = new javax.swing.JLabel();
        tf_jumlahproduk = new javax.swing.JTextField();
        lb_jumlahproduk = new javax.swing.JLabel();
        lb_totalproduk = new javax.swing.JLabel();
        lb_gentotalproduk = new javax.swing.JLabel();
        bt_belanja = new javax.swing.JButton();
        bt_hitung1 = new javax.swing.JButton();
        lb_menubelanja = new javax.swing.JLabel();
        rekening = new javax.swing.JPanel();
        riwayat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_riwayat = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jenis_transaksi = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 720));

        header.setBackground(new java.awt.Color(0, 128, 128));
        header.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 128, 128)));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnMaximize.setBackground(new java.awt.Color(0, 128, 128));
        btnMaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/max.png"))); // NOI18N
        btnMaximize.setContentAreaFilled(false);
        btnMaximize.setFocusable(false);
        btnMaximize.setOpaque(true);
        btnMaximize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/max.png"))); // NOI18N
        btnMaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseExited(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(0, 128, 128));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnExit.setContentAreaFilled(false);
        btnExit.setFocusable(false);
        btnExit.setOpaque(true);
        btnExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        btnMinimize.setBackground(new java.awt.Color(0, 128, 128));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/min.png"))); // NOI18N
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setFocusable(false);
        btnMinimize.setOpaque(true);
        btnMinimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/min.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });

        title.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Beranda - Basara 1.0");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMaximize, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
            .addComponent(btnMaximize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        header2.setBackground(new java.awt.Color(255, 255, 255));
        header2.setForeground(new java.awt.Color(0, 128, 128));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-40.png"))); // NOI18N
        jButton11.setContentAreaFilled(false);

        jButton12.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton12.setText("Nama Pengguna");
        jButton12.setContentAreaFilled(false);
        jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-exit-20.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Logout");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/basara.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Helo,");

        javax.swing.GroupLayout header2Layout = new javax.swing.GroupLayout(header2);
        header2.setLayout(header2Layout);
        header2Layout.setHorizontalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        header2Layout.setVerticalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(header2Layout.createSequentialGroup()
                .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(header2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(header2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(header2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 128, 128));

        pnlBeranda.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlBerandaLayout = new javax.swing.GroupLayout(pnlBeranda);
        pnlBeranda.setLayout(pnlBerandaLayout);
        pnlBerandaLayout.setHorizontalGroup(
            pnlBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        pnlBerandaLayout.setVerticalGroup(
            pnlBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconBeranda.setBackground(new java.awt.Color(0, 128, 128));
        iconBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        iconBeranda.setContentAreaFilled(false);
        iconBeranda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iconBeranda.setOpaque(true);
        iconBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconBerandaMouseClicked(evt);
            }
        });

        btnBeranda.setBackground(new java.awt.Color(0, 128, 128));
        btnBeranda.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnBeranda.setForeground(new java.awt.Color(255, 255, 255));
        btnBeranda.setText("Beranda");
        btnBeranda.setContentAreaFilled(false);
        btnBeranda.setFocusable(false);
        btnBeranda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBeranda.setOpaque(true);
        btnBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBerandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBerandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBerandaMouseExited(evt);
            }
        });
        btnBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(iconBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnBeranda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jPanel5.setBackground(new java.awt.Color(0, 128, 128));

        pnlSetor.setBackground(new java.awt.Color(0, 128, 128));

        javax.swing.GroupLayout pnlSetorLayout = new javax.swing.GroupLayout(pnlSetor);
        pnlSetor.setLayout(pnlSetorLayout);
        pnlSetorLayout.setHorizontalGroup(
            pnlSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        pnlSetorLayout.setVerticalGroup(
            pnlSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconSetor.setBackground(new java.awt.Color(255, 255, 255));
        iconSetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        iconSetor.setContentAreaFilled(false);
        iconSetor.setOpaque(true);

        btnSetor.setBackground(new java.awt.Color(255, 255, 255));
        btnSetor.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnSetor.setForeground(new java.awt.Color(114, 115, 118));
        btnSetor.setText("Setor Sampah");
        btnSetor.setContentAreaFilled(false);
        btnSetor.setFocusable(false);
        btnSetor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSetor.setOpaque(true);
        btnSetor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetorMouseClicked(evt);
            }
        });
        btnSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(iconSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSetor, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSetor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconSetor, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnSetor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jPanel6.setBackground(new java.awt.Color(0, 128, 128));

        pnlBelanja.setBackground(new java.awt.Color(0, 128, 128));

        javax.swing.GroupLayout pnlBelanjaLayout = new javax.swing.GroupLayout(pnlBelanja);
        pnlBelanja.setLayout(pnlBelanjaLayout);
        pnlBelanjaLayout.setHorizontalGroup(
            pnlBelanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        pnlBelanjaLayout.setVerticalGroup(
            pnlBelanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconBelanja.setBackground(new java.awt.Color(255, 255, 255));
        iconBelanja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_shopping_cart_30px_4.png"))); // NOI18N
        iconBelanja.setContentAreaFilled(false);
        iconBelanja.setOpaque(true);

        btnBelanja.setBackground(new java.awt.Color(255, 255, 255));
        btnBelanja.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnBelanja.setForeground(new java.awt.Color(114, 115, 118));
        btnBelanja.setText("Belanja");
        btnBelanja.setContentAreaFilled(false);
        btnBelanja.setFocusable(false);
        btnBelanja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBelanja.setOpaque(true);
        btnBelanja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBelanjaMouseClicked(evt);
            }
        });
        btnBelanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBelanjaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlBelanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(iconBelanja, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBelanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBelanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconBelanja, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnBelanja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jPanel10.setBackground(new java.awt.Color(0, 128, 128));

        pnlRekening.setBackground(new java.awt.Color(0, 128, 128));

        javax.swing.GroupLayout pnlRekeningLayout = new javax.swing.GroupLayout(pnlRekening);
        pnlRekening.setLayout(pnlRekeningLayout);
        pnlRekeningLayout.setHorizontalGroup(
            pnlRekeningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        pnlRekeningLayout.setVerticalGroup(
            pnlRekeningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconRekening.setBackground(new java.awt.Color(255, 255, 255));
        iconRekening.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        iconRekening.setContentAreaFilled(false);
        iconRekening.setOpaque(true);

        btnRekening.setBackground(new java.awt.Color(255, 255, 255));
        btnRekening.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnRekening.setForeground(new java.awt.Color(114, 115, 118));
        btnRekening.setText("Rekening");
        btnRekening.setContentAreaFilled(false);
        btnRekening.setFocusable(false);
        btnRekening.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRekening.setOpaque(true);
        btnRekening.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRekeningMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlRekening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(iconRekening, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnRekening, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlRekening, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconRekening, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnRekening, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jPanel12.setBackground(new java.awt.Color(0, 128, 128));

        pnlRiwayat.setBackground(new java.awt.Color(0, 128, 128));

        javax.swing.GroupLayout pnlRiwayatLayout = new javax.swing.GroupLayout(pnlRiwayat);
        pnlRiwayat.setLayout(pnlRiwayatLayout);
        pnlRiwayatLayout.setHorizontalGroup(
            pnlRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        pnlRiwayatLayout.setVerticalGroup(
            pnlRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconRiwayat.setBackground(new java.awt.Color(255, 255, 255));
        iconRiwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        iconRiwayat.setContentAreaFilled(false);
        iconRiwayat.setOpaque(true);

        btnRiwayat.setBackground(new java.awt.Color(255, 255, 255));
        btnRiwayat.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnRiwayat.setForeground(new java.awt.Color(114, 115, 118));
        btnRiwayat.setText("Riwayat");
        btnRiwayat.setContentAreaFilled(false);
        btnRiwayat.setFocusable(false);
        btnRiwayat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRiwayat.setOpaque(true);
        btnRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRiwayatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(iconRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnRiwayat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlRiwayat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconRiwayat, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btnRiwayat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu.setBackground(new java.awt.Color(204, 204, 204));
        menu.setLayout(new java.awt.CardLayout());

        beranda1.setBackground(new java.awt.Color(102, 102, 0));

        javax.swing.GroupLayout beranda1Layout = new javax.swing.GroupLayout(beranda1);
        beranda1.setLayout(beranda1Layout);
        beranda1Layout.setHorizontalGroup(
            beranda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1014, Short.MAX_VALUE)
        );
        beranda1Layout.setVerticalGroup(
            beranda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        menu.add(beranda1, "beranda");

        setor.setBackground(new java.awt.Color(255, 255, 255));
        setor.setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("SETOR SAMPAH");

        lb_namasampah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_namasampah.setText("Nama Sampah");

        lb_ktgsampah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_ktgsampah.setText("Kategori");

        lb_jumlah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_jumlah.setText("Jumlah");

        bt_Setor.setText("Setor");
        bt_Setor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SetorActionPerformed(evt);
            }
        });

        cb_namasampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_namasampahActionPerformed(evt);
            }
        });

        cb_ktgsampah.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_ktgsampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ktgsampahActionPerformed(evt);
            }
        });

        lb_hargasampah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_hargasampah.setText("Harga");

        lb_genhargasampah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lb_total1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_total1.setText("Total");

        lb_gentotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        bt_hitung.setText("Hitung");
        bt_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hitungActionPerformed(evt);
            }
        });

        lb_genhargasampah1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_genhargasampah1.setText("CLOCK");

        lb_date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lb_time.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout setorLayout = new javax.swing.GroupLayout(setor);
        setor.setLayout(setorLayout);
        setorLayout.setHorizontalGroup(
            setorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setorLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(setorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setorLayout.createSequentialGroup()
                        .addComponent(bt_Setor)
                        .addGap(18, 18, 18)
                        .addComponent(bt_hitung))
                    .addComponent(lb_total1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(setorLayout.createSequentialGroup()
                        .addGroup(setorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_namasampah, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_hargasampah, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_ktgsampah, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(setorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_ktgsampah, 0, 115, Short.MAX_VALUE)
                            .addComponent(lb_genhargasampah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_namasampah, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_gentotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_jumlah))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lb_time, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(setorLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(lb_genhargasampah1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        setorLayout.setVerticalGroup(
            setorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setorLayout.createSequentialGroup()
                .addGroup(setorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(setorLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lb_genhargasampah1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_time, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_ktgsampah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_ktgsampah))
                .addGap(22, 22, 22)
                .addGroup(setorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_namasampah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_namasampah, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(setorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_genhargasampah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_hargasampah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(setorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(setorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_total1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_gentotal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(setorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Setor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        menu.add(setor, "setor");

        belanja.setBackground(new java.awt.Color(255, 255, 255));

        lb_ktgproduk.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_ktgproduk.setText("Kategori");

        cb_ktgproduk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_ktgproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ktgprodukActionPerformed(evt);
            }
        });

        cb_namaproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_namaprodukActionPerformed(evt);
            }
        });

        lb_namasampah1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_namasampah1.setText("Nama Produk");

        lb_hargaproduk.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_hargaproduk.setText("Harga");

        lb_genhargaproduk.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lb_jumlahproduk.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_jumlahproduk.setText("Jumlah");

        lb_totalproduk.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_totalproduk.setText("Total");

        lb_gentotalproduk.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        bt_belanja.setText("Belanja");
        bt_belanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_belanjaActionPerformed(evt);
            }
        });

        bt_hitung1.setText("Hitung");
        bt_hitung1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hitung1ActionPerformed(evt);
            }
        });

        lb_menubelanja.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lb_menubelanja.setText("BELANJA");

        javax.swing.GroupLayout belanjaLayout = new javax.swing.GroupLayout(belanja);
        belanja.setLayout(belanjaLayout);
        belanjaLayout.setHorizontalGroup(
            belanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(belanjaLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(belanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(belanjaLayout.createSequentialGroup()
                        .addComponent(bt_belanja)
                        .addGap(18, 18, 18)
                        .addComponent(bt_hitung1))
                    .addComponent(lb_totalproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(belanjaLayout.createSequentialGroup()
                        .addGroup(belanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_namasampah1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_hargaproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_ktgproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_jumlahproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(belanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_ktgproduk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_genhargaproduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_namaproduk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_gentotalproduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_jumlahproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, belanjaLayout.createSequentialGroup()
                .addContainerGap(413, Short.MAX_VALUE)
                .addComponent(lb_menubelanja, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(375, 375, 375))
        );
        belanjaLayout.setVerticalGroup(
            belanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(belanjaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lb_menubelanja, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(belanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_ktgproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_ktgproduk))
                .addGap(22, 22, 22)
                .addGroup(belanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_namasampah1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_namaproduk, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(belanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_genhargaproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_hargaproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(belanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_jumlahproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_jumlahproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(belanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_totalproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_gentotalproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(belanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_belanja, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hitung1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );

        menu.add(belanja, "belanja");

        rekening.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout rekeningLayout = new javax.swing.GroupLayout(rekening);
        rekening.setLayout(rekeningLayout);
        rekeningLayout.setHorizontalGroup(
            rekeningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1014, Short.MAX_VALUE)
        );
        rekeningLayout.setVerticalGroup(
            rekeningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        menu.add(rekening, "rekening");

        riwayat.setBackground(new java.awt.Color(255, 255, 255));

        tb_riwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_riwayat);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setText("RIWAYAT TRANSAKSI");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Jenis Transaksi :");

        jenis_transaksi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout riwayatLayout = new javax.swing.GroupLayout(riwayat);
        riwayat.setLayout(riwayatLayout);
        riwayatLayout.setHorizontalGroup(
            riwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatLayout.createSequentialGroup()
                .addGroup(riwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(riwayatLayout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel4))
                    .addGroup(riwayatLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(riwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(riwayatLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jenis_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        riwayatLayout.setVerticalGroup(
            riwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addGroup(riwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jenis_transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        menu.add(riwayat, "riwayat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseClicked
        if(Maximize){
            Pengguna.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment max = GraphicsEnvironment.getLocalGraphicsEnvironment();
            Pengguna.this.setMaximizedBounds(max.getMaximumWindowBounds());
            Maximize = false;
        }else{
            setExtendedState(JFrame.NORMAL);
            Maximize = true;
        }
    }//GEN-LAST:event_btnMaximizeMouseClicked

    private void btnMaximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseEntered
        btnMaximize.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_btnMaximizeMouseEntered

    private void btnMaximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseExited
        btnMaximize.setBackground(new Color(0, 128, 128));
    }//GEN-LAST:event_btnMaximizeMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(new Color(232, 15, 35));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new Color(0, 128, 128));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        btnMinimize.setBackground(new Color(0, 128, 128));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        if(Maximize){
            int xMouse = evt.getXOnScreen();
            int yMouse = evt.getYOnScreen();
            this.setLocation(xMouse - x, yMouse - y);
        }

    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void btnBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseClicked
        
        btnBeranda.setBackground(new Color(0, 128, 128));
        btnBeranda.setForeground(new Color(255, 255, 255));
        iconBeranda.setBackground(new Color(0, 128, 128));
        pnlBeranda.setBackground(new Color(255, 255, 255));
        title.setText("Beranda - Basara 1.0");
        
        btnSetor.setBackground(new Color(255, 255, 255));
        btnSetor.setForeground(new Color(114, 115, 118));
        iconSetor.setBackground(new Color(255, 255, 255));
        pnlSetor.setBackground(new Color(0, 128, 128));
        
        btnBelanja.setBackground(new Color(255, 255, 255));
        btnBelanja.setForeground(new Color(114, 115, 118));
        iconBelanja.setBackground(new Color(255, 255, 255));
        pnlBelanja.setBackground(new Color(0, 128, 128));
        
        btnRekening.setBackground(new Color(255, 255, 255));
        btnRekening.setForeground(new Color(114, 115, 118));
        iconRekening.setBackground(new Color(255, 255, 255));
        pnlRekening.setBackground(new Color(0, 128, 128));
        
        btnRiwayat.setBackground(new Color(255, 255, 255));
        btnRiwayat.setForeground(new Color(114, 115, 118));
        iconRiwayat.setBackground(new Color(255, 255, 255));
        pnlRiwayat.setBackground(new Color(0, 128, 128));
        
        cardlayout.show(menu, "beranda");

    }//GEN-LAST:event_btnBerandaMouseClicked

    private void iconBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconBerandaMouseClicked

    }//GEN-LAST:event_iconBerandaMouseClicked

    private void btnBerandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseEntered

    }//GEN-LAST:event_btnBerandaMouseEntered

    private void btnBerandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseExited

    }//GEN-LAST:event_btnBerandaMouseExited

    private void btnBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerandaActionPerformed

    }//GEN-LAST:event_btnBerandaActionPerformed

    private void btnSetorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetorMouseClicked
        cardlayout.show(menu,"setor");
        btnBeranda.setBackground(new Color(255, 255, 255));
        btnBeranda.setForeground(new Color(114, 115, 118));
        iconBeranda.setBackground(new Color(255, 255, 255));
        pnlBeranda.setBackground(new Color(0, 128, 128));
        
        btnSetor.setBackground(new Color(0, 128, 128));
        btnSetor.setForeground(new Color(255, 255, 255));
        iconSetor.setBackground(new Color(0, 128, 128));
        pnlSetor.setBackground(new Color(255, 255, 255));
        title.setText("Setor - Basara 1.0");
        
        btnBelanja.setBackground(new Color(255, 255, 255));
        btnBelanja.setForeground(new Color(114, 115, 118));
        iconBelanja.setBackground(new Color(255, 255, 255));
        pnlBelanja.setBackground(new Color(0, 128, 128));
        
        btnRekening.setBackground(new Color(255, 255, 255));
        btnRekening.setForeground(new Color(114, 115, 118));
        iconRekening.setBackground(new Color(255, 255, 255));
        pnlRekening.setBackground(new Color(0, 128, 128));
        
        btnRiwayat.setBackground(new Color(255, 255, 255));
        btnRiwayat.setForeground(new Color(114, 115, 118));
        iconRiwayat.setBackground(new Color(255, 255, 255));
        pnlRiwayat.setBackground(new Color(0, 128, 128));
        
        cardlayout.show(menu, "setor");
        
    }//GEN-LAST:event_btnSetorMouseClicked

    private void btnBelanjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBelanjaMouseClicked
        btnBeranda.setBackground(new Color(255, 255, 255));
        btnBeranda.setForeground(new Color(114, 115, 118));
        iconBeranda.setBackground(new Color(255, 255, 255));
        pnlBeranda.setBackground(new Color(0, 128, 128));
        
        btnSetor.setBackground(new Color(255, 255, 255));
        btnSetor.setForeground(new Color(114, 115, 118));
        iconSetor.setBackground(new Color(255, 255, 255));
        pnlSetor.setBackground(new Color(0, 128, 128));
        
        btnBelanja.setBackground(new Color(0, 128, 128));
        btnBelanja.setForeground(new Color(255, 255, 255));
        iconBelanja.setBackground(new Color(0, 128, 128));
        pnlBelanja.setBackground(new Color(255, 255, 255));
        title.setText("Belanja - Basara 1.0");
        
        btnRekening.setBackground(new Color(255, 255, 255));
        btnRekening.setForeground(new Color(114, 115, 118));
        iconRekening.setBackground(new Color(255, 255, 255));
        pnlRekening.setBackground(new Color(0, 128, 128));
        
        btnRiwayat.setBackground(new Color(255, 255, 255));
        btnRiwayat.setForeground(new Color(114, 115, 118));
        iconRiwayat.setBackground(new Color(255, 255, 255));
        pnlRiwayat.setBackground(new Color(0, 128, 128));
        
        iconBelanja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_shopping_cart_30px_5.png")));
        cardlayout.show(menu, "belanja");
        
    }//GEN-LAST:event_btnBelanjaMouseClicked

    private void btnRekeningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRekeningMouseClicked
        btnBeranda.setBackground(new Color(255, 255, 255));
        btnBeranda.setForeground(new Color(114, 115, 118));
        iconBeranda.setBackground(new Color(255, 255, 255));
        pnlBeranda.setBackground(new Color(0, 128, 128));
        
        btnSetor.setBackground(new Color(255, 255, 255));
        btnSetor.setForeground(new Color(114, 115, 118));
        iconSetor.setBackground(new Color(255, 255, 255));
        pnlSetor.setBackground(new Color(0, 128, 128));
        
        btnBelanja.setBackground(new Color(255, 255, 255));
        btnBelanja.setForeground(new Color(114, 115, 118));
        iconBelanja.setBackground(new Color(255, 255, 255));
        pnlBelanja.setBackground(new Color(0, 128, 128));
        
        btnRekening.setBackground(new Color(0, 128, 128));
        btnRekening.setForeground(new Color(255, 255, 255));
        iconRekening.setBackground(new Color(0, 128, 128));
        pnlRekening.setBackground(new Color(255, 255, 255));
        title.setText("Rekening - Basara 1.0");
        
        btnRiwayat.setBackground(new Color(255, 255, 255));
        btnRiwayat.setForeground(new Color(114, 115, 118));
        iconRiwayat.setBackground(new Color(255, 255, 255));
        pnlRiwayat.setBackground(new Color(0, 128, 128));
        
        cardlayout.show(menu, "rekening");
    }//GEN-LAST:event_btnRekeningMouseClicked

    private void btnRiwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRiwayatMouseClicked
        btnBeranda.setBackground(new Color(255, 255, 255));
        btnBeranda.setForeground(new Color(114, 115, 118));
        iconBeranda.setBackground(new Color(255, 255, 255));
        pnlBeranda.setBackground(new Color(0, 128, 128));
        
        btnSetor.setBackground(new Color(255, 255, 255));
        btnSetor.setForeground(new Color(114, 115, 118));
        iconSetor.setBackground(new Color(255, 255, 255));
        pnlSetor.setBackground(new Color(0, 128, 128));
        
        btnBelanja.setBackground(new Color(255, 255, 255));
        btnBelanja.setForeground(new Color(114, 115, 118));
        iconBelanja.setBackground(new Color(255, 255, 255));
        pnlBelanja.setBackground(new Color(0, 128, 128));
        
        btnRekening.setBackground(new Color(255, 255, 255));
        btnRekening.setForeground(new Color(114, 115, 118));
        iconRekening.setBackground(new Color(255, 255, 255));
        pnlRekening.setBackground(new Color(0, 128, 128));
        
        btnRiwayat.setBackground(new Color(0, 128, 128));
        btnRiwayat.setForeground(new Color(255, 255, 255));
        iconRiwayat.setBackground(new Color (0, 128, 128));
        pnlRiwayat.setBackground(new Color(255, 255, 255));
        title.setText("Riwayat - Basara 1.0");
        cardlayout.show(menu, "riwayat");
    }//GEN-LAST:event_btnRiwayatMouseClicked

    private void btnBelanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBelanjaActionPerformed
        cardlayout.show(menu, "belanja");
    }//GEN-LAST:event_btnBelanjaActionPerformed

    private void btnSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSetorActionPerformed

    private void cb_namasampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_namasampahActionPerformed
       lb_genhargasampah.setText(atributController.getByCondition("harga_beli", "sampah", "nama='"+cb_namasampah.getSelectedItem()+"'"));
    }//GEN-LAST:event_cb_namasampahActionPerformed

    private void cb_ktgsampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ktgsampahActionPerformed
          setAtribut(atributController.getAllData("nama","sampah",("kategori='"+cb_ktgsampah.getSelectedItem()+"'")),cb_namasampah);
    }//GEN-LAST:event_cb_ktgsampahActionPerformed

    private void bt_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hitungActionPerformed
       double total=0;
       total = Double.parseDouble(tf_jumlah.getText())*Double.parseDouble(lb_genhargasampah.getText());
      lb_gentotal.setText(Double.toString(total));
              
       
    }//GEN-LAST:event_bt_hitungActionPerformed

    private void bt_SetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SetorActionPerformed
        String id_setor = "1111111";
        String tgl_setor = lb_date.getText();
        String waktu_setor = lb_time.getText();
        int jumlah = Integer.parseInt(tf_jumlah.getText());
        String Status = "PENDING";
        Double total = Double.parseDouble(lb_gentotal.getText());
        
        String kode_sampah = atributController.getByCondition("kode_Sampah", "sampah", "nama='"+cb_namasampah.getSelectedItem()+"'");
        String no_pengguna = "12345678";
        String kode_branch = "BR01";
        
        
        Transaksi p = new Transaksi(id_setor, tgl_setor, waktu_setor, jumlah,Status, kode_sampah, no_pengguna, "PGW110", kode_branch);        
        transaksiController.manipulate(p,CrudState.INSERT, "setor_sampah");
    }//GEN-LAST:event_bt_SetorActionPerformed

    private void cb_ktgprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ktgprodukActionPerformed
      setAtribut(atributController.getAllData("nama","produk",("kategori='"+cb_ktgproduk.getSelectedItem()+"'")),cb_namaproduk);
    }//GEN-LAST:event_cb_ktgprodukActionPerformed

    private void cb_namaprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_namaprodukActionPerformed
       lb_genhargaproduk.setText(atributController.getByCondition("harga_jual", "produk", "nama='"+cb_namaproduk.getSelectedItem()+"'"));
    }//GEN-LAST:event_cb_namaprodukActionPerformed

    private void bt_belanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_belanjaActionPerformed
        String id_belanja = "1111111";
        String tgl_belanja = lb_date.getText();
        String waktu_belanja = lb_time.getText();
        int jumlah_produk = Integer.parseInt(tf_jumlahproduk.getText());
        String Status = "PENDING";
        Double total = Double.parseDouble(lb_gentotalproduk.getText());
        
        String kode_produk = atributController.getByCondition("kode_produk", "produk", "nama='"+cb_namaproduk.getSelectedItem()+"'");
        String no_pengguna = "12345678";
        String kode_branch = "BR01";
        
        
        Transaksi p = new Transaksi(id_belanja, tgl_belanja, waktu_belanja, jumlah_produk,Status, kode_produk, no_pengguna, "PGW110", kode_branch);        
        transaksiController.manipulate(p,CrudState.INSERT, "belanja_produk");
    }//GEN-LAST:event_bt_belanjaActionPerformed

    private void bt_hitung1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hitung1ActionPerformed
       double total=0;
       total = Double.parseDouble(tf_jumlahproduk.getText())*Double.parseDouble(lb_genhargaproduk.getText());
      lb_gentotalproduk.setText(Double.toString(total));
    }//GEN-LAST:event_bt_hitung1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengguna().setVisible(true);
            }
        });
    }

    
    
    private void setAtribut(java.util.List<Atribut> categories, javax.swing.JComboBox cb){    
        if (categories==null){
            JOptionPane.showMessageDialog(this, "Data kategori gagal diambil dari database","DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
        }else{
            cb.setModel(new DefaultComboBoxModel(categories.toArray()));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel belanja;
    private javax.swing.JPanel beranda1;
    private javax.swing.JButton bt_Setor;
    private javax.swing.JButton bt_belanja;
    private javax.swing.JButton bt_hitung;
    private javax.swing.JButton bt_hitung1;
    private javax.swing.JButton btnBelanja;
    private javax.swing.JButton btnBeranda;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMaximize;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnRekening;
    private javax.swing.JButton btnRiwayat;
    private javax.swing.JButton btnSetor;
    private javax.swing.JComboBox cb_ktgproduk;
    private javax.swing.JComboBox cb_ktgsampah;
    private javax.swing.JComboBox cb_namaproduk;
    private javax.swing.JComboBox cb_namasampah;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header2;
    private javax.swing.JButton iconBelanja;
    private javax.swing.JButton iconBeranda;
    private javax.swing.JButton iconRekening;
    private javax.swing.JButton iconRiwayat;
    private javax.swing.JButton iconSetor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jenis_transaksi;
    private javax.swing.JLabel lb_date;
    private javax.swing.JLabel lb_genhargaproduk;
    private javax.swing.JLabel lb_genhargasampah;
    private javax.swing.JLabel lb_genhargasampah1;
    private javax.swing.JLabel lb_gentotal;
    private javax.swing.JLabel lb_gentotalproduk;
    private javax.swing.JLabel lb_hargaproduk;
    private javax.swing.JLabel lb_hargasampah;
    private javax.swing.JLabel lb_jumlah;
    private javax.swing.JLabel lb_jumlahproduk;
    private javax.swing.JLabel lb_ktgproduk;
    private javax.swing.JLabel lb_ktgsampah;
    private javax.swing.JLabel lb_menubelanja;
    private javax.swing.JLabel lb_namasampah;
    private javax.swing.JLabel lb_namasampah1;
    private javax.swing.JLabel lb_time;
    private javax.swing.JLabel lb_total1;
    private javax.swing.JLabel lb_totalproduk;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel pnlBelanja;
    private javax.swing.JPanel pnlBeranda;
    private javax.swing.JPanel pnlRekening;
    private javax.swing.JPanel pnlRiwayat;
    private javax.swing.JPanel pnlSetor;
    private javax.swing.JPanel rekening;
    private javax.swing.JPanel riwayat;
    private javax.swing.JPanel setor;
    private javax.swing.JTable tb_riwayat;
    private javax.swing.JTextField tf_jumlah;
    private javax.swing.JTextField tf_jumlahproduk;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (o==transaksiController){
            if (arg==null){
                JOptionPane.showMessageDialog(this, "Produk gagal ditambah ke database");
            }else{            
                Transaksi p = (Transaksi) arg;
                if (transaksiController.getCrudState() == CrudState.INSERT){
                    JOptionPane.showMessageDialog(this, " berhasil ditambahkan");
                }
             
            }            
        }
    }


    
    
}
